In [2]:
import torch


In [3]:
#one_axis:vector
#two_axis:matrix
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [6]:
x.numel()
x.shape

torch.Size([12])

In [7]:
X = x.reshape(4,3)
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [9]:
#OR
X = x.reshape(-1,3)
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [11]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [14]:
X[-1], X[0:3]

(tensor([ 9., 10., 11.]),
 tensor([[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]))

In [16]:
X[-1,2] = 0
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10.,  0.]])

In [25]:
X[:3,:] = 12
X

tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.],
        [ 9., 10.,  0.]])

In [27]:
torch.exp(x) #unary_operator = R->R

tensor([1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05,
        1.6275e+05, 1.6275e+05, 1.6275e+05, 8.1031e+03, 2.2026e+04, 1.0000e+00])

In [29]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  #Binary_operators=R,R->R

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [33]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [34]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [35]:
X.sum()

tensor(66.)

In [48]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(4).reshape((1,4))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2, 3]]))

In [49]:
a + b

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])

In [38]:
#We can assign the result of an operation to a previously allocated array Y by using slice notation: Y[:] = <expression>.

In [41]:
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:] = X + Y
print('id(Z):',id(Z))

id(Z): 140236729055920
id(Z): 140236729055920


In [1]:
#Day-2
#Data-Preprocessing

In [4]:
import os
os.makedirs(os.path.join('..','data'), exist_ok=True)
data_file = os.path.join('..','data','tiny_house.csv')
with open(data_file,'w') as f:
    f.write('''NumRooms,Rooftype,Price
    NA,NA,127500
    2,NA,106000
    4,SLATE,178100
    NA,NA,140000''')

In [5]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

  NumRooms Rooftype   Price
0       NA      NaN  127500
1        2      NaN  106000
2        4    SLATE  178100
3       NA      NaN  140000


In [6]:
inputs, targets = data.iloc[:,0:2],data.iloc[:,2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms_    2  NumRooms_    4  NumRooms_    NA  NumRooms_nan  \
0           False           False             True         False   
1            True           False            False         False   
2           False            True            False         False   
3           False           False             True         False   

   Rooftype_SLATE  Rooftype_nan  
0           False          True  
1           False          True  
2            True         False  
3           False          True  


In [7]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms_    2  NumRooms_    4  NumRooms_    NA  NumRooms_nan  \
0           False           False             True         False   
1            True           False            False         False   
2           False            True            False         False   
3           False           False             True         False   

   Rooftype_SLATE  Rooftype_nan  
0           False          True  
1           False          True  
2            True         False  
3           False          True  


In [8]:
#SCALARS
import torch

In [9]:
#element-wise-dot-product in tensors is called Hadamard product


In [10]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [14]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
A.sum(axis=0), A.sum(axis=1)

(tensor([3., 5., 7.]), tensor([ 3., 12.]))

In [15]:
A.sum(axis=[0, 1]) == A.sum() # Same as A.sum()

tensor(True)

In [16]:
#numel: number of elements
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [17]:
A.shape[0]

2

In [20]:
sumA = A.sum(axis=1, keepdims=True)
sumA, sumA.shape


(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [21]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [23]:
A / sumA

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [25]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [26]:
y = torch.ones(3,dtype = torch.float32)
x, y, torch.dot(x,y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [28]:
torch.sum(x*y) #DOTProduct

tensor(3.)

In [29]:
A.shape

torch.Size([2, 3])

In [30]:
x.shape

torch.Size([3])

In [31]:
torch.mv(A,x) == A@x

tensor([True, True])

In [32]:
B = torch.ones(3,4)
torch.mm(A,B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [33]:
#HADAMARD : Element wise
#Dot product: Mul + sum

In [35]:
u = torch.tensor([3.0,-4.0]) #L2-norm
torch.norm(u)

tensor(5.)

In [36]:
torch.abs(u).sum() #L1-norm

tensor(7.)